function Trial07 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRIAL07 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  TRIAL07 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Trial07 = importfile("E:\PostPhD\Projects\C3\Testing data\Test1\Trial07.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jun-2022 15:22:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Trial", "General", "FootStrike", "Time", "TheInstantTheHeelStrikesTheGround"];
opts.VariableTypes = ["double", "char", "categorical", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "General", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["General", "FootStrike", "TheInstantTheHeelStrikesTheGround"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Trial", "TrimNonNumeric", true);
opts = setvaropts(opts, "Trial", "ThousandsSeparator", ",");

% Import the data
Trial07 = readtable(filename, opts);

end