
disp('test');
opensense_dir = 'C:\GBW_MyPrograms\OpenSim_4.1';

mex_command = ['mex ', ...
    [ '-I',opensense_dir],...
    [' -I',opensense_dir,'\bin'],...
    [' -I',opensense_dir,'\sdk\Simbody\include'],...    
    [' -I',opensense_dir,'\sdk\include'],... 
    [' -I',opensense_dir,'\sdk\include\OpenSim'],... 
    [' -I',opensense_dir,'\sdk\include\OpenSim\Common'],...
    [' -I',opensense_dir,'\sdk\include\SimTK\include'],...
    [' -L',opensense_dir,'\sdk\Simbody\lib'],...    
    [' -L',opensense_dir,'\sdk\lib'],...
    ' -losimSimulation.lib', ' -losimActuators', ' -losimCommon', ' -losimAnalyses',...
    ' -losimTools', ' -lSimTKcommon', ' -lSimTKmath', ' -lSimTKsimbody', ' Create_IMU_Storage.cpp'];
eval(mex_command);
